Flag sets
splitio/javascript-browser-client pull request #100
Opened 2023-10-26 21:13 UTC by emmaz90

# JS Browser SDK

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2023-10-30 13:33 UTC, mmelograno approved these changes

2023-10-30 18:51 UTC, EmilianoSanchez requested changes

2023-10-30 18:51 UTC, EmilianoSanchez commented on .github/workflows/ci-cd.yml
> +        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/sdks-7668' || github.ref == 'refs/heads/main') }}
`sdks-7668` -> `development`

2023-10-31 20:52 UTC, EmilianoSanchez approved these changes

2023-11-01 14:15 UTC, EmilianoSanchez requested changes

2023-11-01 14:15 UTC, EmilianoSanchez commented on types/splitio.d.ts
> +  type SplitFilterType = 'bySet' | 'byName' | 'byPrefix';
missing the `sets` property in SplitView type.
Check https://github.com/splitio/react-native-client/pull/71

2023-11-03 22:04 UTC, mmelograno approved these changes

2023-11-03 22:05 UTC, EmilianoSanchez approved these changes

2023-11-03 22:15 UTC, merged